version: "3.8"
services:
  app:
    build: ./backend
    command: npx ts-node-dev --respawn --transpile-only ./src/app.ts
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app

  python-app:
    build: ./python_service
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=HeliosChenThomasBuckley
      - DB_HOST=db.fxxqwotagugztamftphi.supabase.co
      - DB_PORT=5432
    volumes:
      - ./python_service:/usr/src/app
