version: "3.8"
services:
  app:
    build: ./backend
    command: npx ts-node-dev --respawn --transpile-only ./src/app.ts
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - python-app

  python-app:
    build: ./python_service
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres.fxxqwotagugztamftphi
      - DB_PASS=HeliosChenThomasBuckley
      - DB_HOST=aws-0-eu-west-2.pooler.supabase.com
      - DB_PORT=5432
    volumes:
      - ./python_service:/usr/src/app
