import {
  AlertCircle,
  Home,
  Settings,
  User2,
  X,
  CheckCircle,
  Lock,
  Mail,
  MessagesSquare,
  Heart,
  LogOut,
  Bell,
  BadgeCheck,
  MapPin,
  ChevronsRight,
  UserRoundPlus,
  MoreHorizontal,
  ChevronsUpDown,
  FileUp,
  Pencil,
  User,
  SendHorizonal,
} from 'lucide-react';

export const Icons = {
  settings: Settings,
  alertCircle: AlertCircle,
  user: User2,
  close: X,
  home: Home,
  mail: Mail,
  lock: Lock,
  messages: MessagesSquare,
  heart: Heart,
  checkCircle: CheckCircle,
  signOut: LogOut,
  bell: Bell,
  verify: BadgeCheck,
  location: MapPin,
  right: ChevronsRight,
  connect: UserRoundPlus,
  more: MoreHorizontal,
  upDown: ChevronsUpDown,
  upload: FileUp,
  ellipsis: MoreHorizontal,
  pencil: Pencil,
  user1: User,
  send: SendHorizonal
};
