import {
  AlertCircle,
  Home,
  Settings,
  User2,
  X,
  Lock,
  Mail,
  MessagesSquare,
  Heart,
  LogOut,
  Bell,
  BadgeCheck,
  MapPin,
  ChevronsRight,
  UserRoundPlus,
  MoreHorizontal,
} from 'lucide-react';

export const Icons = {
  settings: Settings,
  alertCircle: AlertCircle,
  user: User2,
  close: X,
  home: Home,
  mail: Mail,
  lock: Lock,
  messages: MessagesSquare,
  heart: Heart,
  signOut: LogOut,
  bell: Bell,
  verify: BadgeCheck,
  location: MapPin,
  right: ChevronsRight,
  connect: UserRoundPlus,
  more: MoreHorizontal,
};
